@startuml packages
set namespaceSeparator none
package "app" as app {
}
package "app.asgi" as app.asgi {
}
package "app.backend" as app.backend {
}
package "app.backend.admin" as app.backend.admin {
}
package "app.backend.apps" as app.backend.apps {
}
package "app.backend.migrations" as app.backend.migrations {
}
package "app.backend.migrations.0001_initial" as app.backend.migrations.0001_initial {
}
package "app.backend.migrations.0002_alter_errormodel_name_alter_errormodel_timestamp_end_and_more" as app.backend.migrations.0002_alter_errormodel_name_alter_errormodel_timestamp_end_and_more {
}
package "app.backend.models" as app.backend.models {
}
package "app.backend.serializers" as app.backend.serializers {
}
package "app.backend.tests" as app.backend.tests {
}
package "app.backend.views" as app.backend.views {
}
package "app.settings" as app.settings {
}
package "app.urls" as app.urls {
}
package "app.wsgi" as app.wsgi {
}
app.backend.serializers --> app.backend.models
app.backend.views --> app.backend.models
app.backend.views --> app.backend.serializers
app.urls --> app.backend.views
@enduml
