# Generated by Django 5.1.3 on 2024-12-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errormodel',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='timestamp_end',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='timestamp_start',
            field=models.FloatField(null=True),
        ),
    ]
