# Generated by Django 5.1.3 on 2024-12-27 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_errormodel_name_alter_errormodel_timestamp_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='errormodel',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='errormodel',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='backend.ticketmodel'),
        ),
    ]
