# Generated by Django 5.1.3 on 2025-01-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_errormodel_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errormodel',
            name='progress',
        ),
    ]
