# Generated by Django 5.1.3 on 2025-01-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_errormodel_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='errormodel',
            name='gfi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='errormodel',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='errormodel',
            name='wpm',
            field=models.FloatField(null=True),
        ),
    ]
